{
  "Axios Request Function": {
    "prefix": "api-req",
    "body": [
      "import axios from \"axios\";",
      "",
      "type ${1:${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/}}RequestProps = {",
      "  $0",
      "};",
      "",
      "type ${1:${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/}}ResponseProps = {",
      "",
      "};",
      "",
      "export async function ${2:${TM_FILENAME_BASE/(.*)/${1:/camelcase}/}}(req: ${1:${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/}}RequestProps): Promise<${1:${TM_FILENAME_BASE/(.*)/${1:/pascalcase}/}}ResponseProps> {",
      "  try {",
      "    const response = await axios.${3|post,get,put,delete|}(`\\${import.meta.env.VITE_SERVER_URL}/${4:endpoint}`, req);",
      "    return Promise.resolve(response.data);",
      "  } catch (error) {",
      "    if (axios.isAxiosError(error)) {",
      "      if (error.response) {",
      "        console.log(error.response);",
      "        return Promise.reject(new Error(\"${5:Error message}\"));",
      "      }",
      "    }",
      "    if (error instanceof Error) {",
      "      console.error(error);",
      "      alert(error.message);",
      "    }",
      "    console.error(\"An unexpected error occurred:\", error);",
      "    alert(\"An unexpected error occurred\");",
      "    return Promise.reject(error);",
      "  }",
      "}"
    ],
    "description": "Axios request function template with error handling"
  }
}
